### ISSUE TITLE
How do I interpret the options in the GUI?

### ISSUE THREAD

**Issue by person4268** [cavallium/Midi23D#2]
They just seem somewhat confusing to me. I'm pretty sure that Motor X,Y,Z are for the steps/mm of the motors, but I'm not sure at all how to interpret the images with the text boxes at the bottom and what it means, though I guess they relate to properly setting the size of the area. Adding some tooltips or explaining what they do would be nice!

**Comment by Cavallium** [comment]
Unfortunately I didn't touch this project in years, I was rewriting it from scratch a lot of time ago because the current source code is a mess, but then I abandoned the project.

If I find some time I'll add the tooltips.

**Comment by person4268** [comment]
Thanks for replying. I just ended up using the cli version after figuring it out how to activate it from the source code. 
For anyone else reading, I did `java -jar midi23d.jar input.mid output.gcode 1 1 false` iirc.
